version: '2'
services:
  tahrir:
    build:
      context: './Application'
      dockerfile: './Dockerfile'
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
    - ./Application:/opt/tahrir
    entrypoint: "./docker-entrypoint.sh"
    restart: unless-stopped
  nginx:
    image: nginx:1.16
    links:
      - tahrir:tahrir
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
      - 4000:443
  postgres:
    build:
      context: './PostgreSQL'
      dockerfile: './Dockerfile'
    restart: unless-stopped
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/backup/:/backup 
