version: '3'
services:
  tahrir:
    build:
      context: .
      dockerfile: './Dockerfile'
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
    - .:/opt/tahrir
    restart: unless-stopped
  nginx:
    image: nginx:1.16
    links:
      - tahrir:tahrir
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
      - 4000:443
  postgres:
    image: postgres:11
    restart: unless-stopped
    volumes:
      -  ./volumes/postgres/data:/var/lib/postgresql/data
