version: '3'
services:
  tahrir:
    build:
      context: .
      dockerfile: './Dockerfile'
    ports:
      - "55555:55555"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
    - .:/opt/jarchi
    restart: unless-stopped
  nginx:
    image: nginx:1.16
    links:
      - tahrir:tahrir
    restart: unless-stopped
  postgres:
    image: postgres:11
    restart: unless-stopped
    volumes:
      -  ./volumes/postgres/data:/var/lib/postgresql/data
