# Generated by Django 2.2.2 on 2019-07-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TahrirBackend', '0003_auto_20190701_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entofatranslation',
            options={'verbose_name': 'English To Farsi', 'verbose_name_plural': 'English To Farsi s'},
        ),
        migrations.AlterModelOptions(
            name='fatoentranslation',
            options={'verbose_name': 'Farsi To English', 'verbose_name_plural': 'Farsi To English s'},
        ),
        migrations.AddField(
            model_name='englishword',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persianword',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
