# Generated by Django 2.2.2 on 2019-07-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TahrirBackend', '0005_auto_20190702_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entofatranslation',
            options={'verbose_name': 'English To Farsi', 'verbose_name_plural': 'English To Farsi'},
        ),
        migrations.AlterModelOptions(
            name='fatoentranslation',
            options={'verbose_name': 'Farsi To English', 'verbose_name_plural': 'Farsi To English'},
        ),
    ]
