# Generated by Django 2.2.2 on 2019-07-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TahrirBackend', '0002_auto_20190701_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatoentranslation',
            name='submitter_name',
            field=models.CharField(max_length=50),
        ),
    ]
