# Generated by Django 2.2.2 on 2019-07-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TahrirBackend', '0004_auto_20190702_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishword',
            name='suggested_to_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persianword',
            name='suggested_to_translate',
            field=models.BooleanField(default=False),
        ),
    ]
