# Generated by Django 2.2.2 on 2019-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TahrirBackend', '0006_auto_20190702_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entofatranslation',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fatoentranslation',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
